%% The tex file is not to be edited; it is generated.
%% Only edit .Rnw file

\documentclass[nojss]{jss}

\usepackage[utf8]{inputenc}
\usepackage{amsmath, bm}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{url}
\usepackage{natbib}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{multicol}
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\ErrorTok}[1]{\textbf{{#1}}}
\newcommand{\NormalTok}[1]{{#1}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% declarations for jss.cls %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\author{\begin{tabular}{*{2}{>{\centering}p{.5\textwidth}}}
\large Nome1 & \large Nome2 \tabularnewline
Department1 & Department2 \tabularnewline
School1 & School2 \tabularnewline
\url{url1} & \url{url2}
\end{tabular}
}


\author{
Yujing Jiang\\ University of Connecticut \And
  Xin He\\ University of Maryland \And
  Mei-Ling Ting Lee\\ University of Maryland \AND
  Bernard Rosner\\ Harvard University  \And
  Jun Yan\\ University of Connecticut
  }
\title{Rank-Based Tests for Clustered Data with \proglang{R} Package
\pkg{clusrank}}

%% for pretty printing and a nice hypersummary also set:
\Plainauthor{Yujing Jiang, Mei-Ling Ting Lee, Jun Yan} %% comma-separated
\Plaintitle{R package Clustered Wilcoxon Rank Sum Test and Signed Rank Test} %% without formatting
\Shorttitle{Rank tests for cluster data} %% a short title (if necessary)

%% an abstract and keywords


\Abstract{
Rank based tests are popular distribution-free alternatives to 
the popular one-sample and two-sample $t$-tests.
For independent data, they are available in
the \pkg{base} package of \proglang{R}.
For clustered data, several rank-based tests that accounts for
the within-cluster dependence are recently developed, but no existing
package provides all of them at one place with ease of access.
In package \pkg{clusrank}, the latest developments are implemented
and wrapped under a unified high-level user-friendly function.
Different methods are dispatched based on an input formula, 
offering great flexibility in handling various situations such as 
unbalanced cluster sizes, presence of ties, stratified data, 
and heterogeneous group members from the same cluster. 
Methods based on both asymptotics for large samples and
permutation for small samples are available.
We present some details about the implemented methods and a 
comprehensive comparison of them in a simulation study.
}


\Keywords{Wilcoxon rank sum test, Wilcoxon signed rank test}
\Plainkeywords{Wilcoxon rank sum test, Wilcoxon signed rank test}

%% without formatting
%% at least one keyword must be supplied

%% publication information
%% NOTE: Typically, this can be left commented and will be filled out by the technical editor
%% \Volume{50}
%% \Issue{9}
%% \Month{June}
%% \Year{2012}
%% \Submitdate{2012-06-04}
%% \Acceptdate{2012-06-04}

%% The address of (at least) one author should be given
%% in the following format:

\Address{
  Yujing Jiang and Jun Yan\\
  Department of Statistics\\
  Professor of Statistics\\
  University of Connecticut\\
  215 Glenbrook Rd. Unit 4120, Storrs, CT 06269, USA.\\
  Email: \email{yujing.jiang@uconn.edu}, \email{jun.yan@uconn.edu}
  
  Xin He and Mei-Ling Ting Lee\\
  Department of Epidemiology and Biostatistics\\
  University of Maryland\\
  EPIB 2234R, SPH Building \#255,  College Park, MD 20742, USA.\\
  Email: \email{xinhe@umd.edu}, \email{mltlee@umd.edu}
  
  Bernard Rosner\\
  Department of Biostatistics\\
  Harvard University\\
  180 Longwood Avenue,  Boston, Massachusetts 02115, USA\\
  Email: \email{stbar@channing.harvard.edu}
  
}
%% It is also possible to add a telephone and fax number
%% before the e-mail in the following format:
%% Telephone: +43/512/507-7103
%% Fax: +43/512/507-2851

%% for those who use Sweave please include the following line (with % symbols):
%% need no \usepackage{Sweave.sty}

%% end of declarations %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




%% include your article here, just as usual
%% Note that you should use the \pkg{}, \proglang{} and \code{} commands.
\begin{document}

\section{Introduction}

Clustered data arise in many applications, where the
data are grouped into independent clusters with correlated cluster members.
In an eye study, for instance, the measurements from each individual consist a 
cluster.
When the goal of a study is to compare two populations or the outcome of a 
treatment to a baseline, standard Wilcoxon rank-sum test or signed rank test 
are popular tools if the distribution of the data is non-normal or unknown. 
However, these tests cannot be applied to clustered data directly since the 
effective sample size of the clustered data will be different from the number 
of observations due to non-zero intracluster correlation. As a consequence, the 
p-value will be either under-estimated or over-estimated. 

Recent developments have extended the Wilcoxon rank-sum test 
and signed rank test to clustered data. A Mann-Whitney U statistic for 
clustered data was first proposed by \citet{Rosn:Grov:use:1999}. The variance 
of the test statistic is corrected by four types of intra cluster correlation. 
However, no large sample theory was proved. A large sample test statistic for 
clustered data by conditioning on the cluster size was introduced in 
\citet{Rosn:Glyn:Lee:inco:2003} with asymptotic normality of the null 
distribution justified. This approach also allows data which are stratified by 
an extra covariant.  However, this approach requires that, first, members from 
the same cluster have to belong to the same group; second, there have to be 
clusters from both group for each cluster size. These two requirements was 
later removed in \citet{Datt:Satt:rank:2005}. Also Datta and Satten's approach 
allows comparison between $m(m \geq 3)$ groups. Though, their method is not
able to compare the intracluster difference between two groups. More recently, 
\citet{Rosn:Blyn:Lee:exte:2006} extended their approach to accommodate the 
situation where members of a single cluster may subject to different 
treatments. 

For the one-sample problem (for univariate data), the Wilcoxon
signed-rank test was extended to clusterd data in
\citet{Rosn:Glyn:Lee:wilc:2006} by adjusting the variance of the
standard test statistic for clustering effect, assuming a common intercluster correlation. The cluster sizes are
allowed to vary and a large-aample test was proposed. However, this
method does not consider the situation where the cluster size is
informative, i.e., the distribution of difference within a cluster
depends on the cluster size. The signed rank statistic proposed by
\citet{Datt:Satt:sign:2008} based on sampling within cluster performed
better under scenarios when cluster size is informative.



Despite the popularity of clustered data in a wide range of
applications such as clinical trials, longitudinal study, social
science, and others, and despite the availability of the rank-based
tests for clustered data, we are unaware of any existing \proglang{R}
package that provides functions implementing the methods reviewed
above.  This motivated our development of package \pkg{clusrank} for
rank-based tests for clustered data. Rank sum test from
\citet{Rosn:Glyn:Lee:inco:2003},  \citet{Datt:Satt:rank:2005} and \citet{Deni:etal:two:2010} and
signed rank test from \citet{Rosn:Glyn:Lee:wilc:2006} and
\citet{Datt:Satt:sign:2008} were implemented in this package.

%Large-sample inference based on asymptotic distribution of test
%statistics and small-sample inference based on permutation are
%provided for both rank sum test and signed rank test. 
%The tests provided can also handel unbalanced data when
%there are clusters with different sizes.
%In addition, for rank sum test, the effect of stratification as an
%extra cofounding variable can also be accounted for.


The order of this paper is as following, Section~\ref{sec:test}
introduces test statistics implemented in the package. The interface
of the test functions are presented in Section 3. Section 4 uses a
simulation study to compare the test statistics. Section 5 illustrates
the usage of the package using a real data analysis for a eye
study. THe last section discusses possible extensions of the package.




\textbf{the name sedlab is a poor choice.}


\section{Rank-Based Tests for Clustered Data}
\label{sec:test} 
%% note the label style. It helps to distinguish from
%% table or figure labels.


\subsection{Wilcoxon Rank Sum Test}
\label{ranksum} % DO NOT define if it is not used.

Let $X_{ij}$ denote the $i$th observation in the $j$th cluster,
$1 \leq i \leq N$, $1 \leq j \leq g_i $. There are $N$ clusters
in total, the $i$th cluster contains $g_i$ observations.
Let $\delta_{ij}$ denote the treatment placed on $X_{ij}$,
$\delta{ij} = 1$ if $X_{ij}$ is under treatment $1$,
$\delta{ij} = 0$ if $X_{ij}$ is under treatment $2$.
(The DS method is able to compare $m$ groups.)
\subsubsection{RGL method: unbalanced data}
The RGL method requires that all individuals in a single
cluster belong to the same treatment group, i.e., the
group membership indicators $\delta_{ij}$ for observations in
the $i$th cluster take a identical value, thus we denote the group membership
of the $i$th cluster as $\delta_{i}$.
Let $N_g$ and $m_g$ denote the number of clusters and number of clusters under
treatment 1 with cluster size $g$, respectivly, $g \in \{1, \ldots, g_{max}\}$.
It is also assumed
the observations within any single cluster are exchangable.
Let $R_{ij}$ denote the rank of each observation among all observations.
Then the test statistic $W_{rgl}$ is defined as
$$W_{rgl} = \sum_{i,j}\delta_{ij}R_[ij] = \sum_{i}\delta_iR_{i+}$$,
which is exactly the same as the standard Wilcoxon rank sum test.
The sampling distribution of this test statistic is derived by
conditioning on the cluster size and the number of clusters under treatment $1$
for that specific sample size, i.e., all the clusters are
first stratified based on their cluster size, then the sampling
distribution of each stratum is obtained. Because clusters
are assume to be independent, the expectation and
variance of $W_{rgl}$ are obtained by combining the corresponding
quantities of each stratum. Therefore,
\begin{equation*}
E(W_{rgl}) = \sum_{g = 1}^{g_{max}}m_g(R_{++,g} / N_g)
\end{equation*}
\begin{equation*}
Var(W_{rgl}) = \sum_{g = 1} ^ {g_{max}}[m_g(N_g - m_g) / \{N_g{N_g - 1}\}]
\sum_{i = 1}^{N_g}(R_{i+,g} - R_{++,g} / N_g)^2
\end{equation*}


RGL statistic is also capable of dealing with extra stratification
covariate coming with the scores, e.g., data from multiple medical centers where
each center can be treated as a stratum. The derivation of the
$E(W_{rgl})$ and $Var(W_{rgl})$ is very similar to the derivation for
unbalanced data. On the basis of the stratums defined by the cluster
size, each stratum is further stratified by the stratifying
covariate. The expectation and variance of the test statistic
restricted to each of these strata is computed by treating each
restriction as an ordinary Wilcoxon rank sum test. Assume there are
$V$ strata, the expectation and variance of $W_{rgl}$ are
\begin{equation*}
E(W_{rgl}) = \sum^{g_{max}}_{g = 1}\sum_{v =
1}^{V}m_{g,v}R_{++, g, v} / N_{g,v}
\end{equation*}
\begin{equation*}
Var(W_{rgl}) = \sum^{g_{max}}_{g=1}\sum_{v = 1}^V[m_{g,v}(N_{g,v} -
m_{g,v}) / \{N_{g,v}(N_{g,v} - 1)\}]\times\sum^{N_{g,v}}_{i=1}(R_{i+, g, v} - R_{++,g,v}/N_{g,v})^2
\end{equation*}
The large sample test statistic with asymptotic normality
is defined as $$Z_{rgl} = \frac{W_{rgl} - E(W_{rlg})}{VAR(W_{rgl})^{1/2}}$$.

\subsubsection{RGL method, group membership defined at the subunit level}



\subsection{DS method: 2 group}
DS construct another rank sum test based on a different idea from
RGL's method. A single individual from each cluster is sampled,
recorded as $X_i^*$ with its group membership $\delta_i^*$,
$1 \leq i \leq M$. A WIlcoxon rank-sum statistic can be defined as
\begin{equation*}
W^* = \frac{1}{M+1}\sum^M_{i=1}\delta^*_iR^*_i,
\end{equation*}
where $R_i^*$ is the rank of $X^*$ among the set $\{X_j^*, 1 \leq j \leq M\}$.
But this test is inefficient since only one observation from each cluster
is used. DS proposed a test statistic which is based on the average of $W^*$
over all possible samples of $\{X_i^*, \delta_i^*\}$, i.e.,
$$Z_{ds} = \frac{S - E(S)}{\sqrt{\hat{var}(S)}}$$, where
$$S = E(W^*|\bm{X}, \bm{\delta})$$.
$$E(W^*) = \frac{1}{2}\sum^M_{i=1}\frac{n_{g_{i1}}}{g_i}$$.
The computation of $Var(S)$ is complicated therefore is not included here in the draft.

Following the same derivation, the DS test can be extended to the comparison
among $m$ groups, $m \geq 3$.




Suppose there are two groups under different treatments,
$X$ and $Y$, the null hypothesis of the rank sum test
is that the probability of an observation from a
treatment $X$ exceeding an observation from treatment
$Y$ is the same as an observation from treatment $Y$
exceeding an observation from treatment $X$.
Specifically,
assume the data came in clusters and
let $X_{ij}$ denote the score for the $j$th subunit
from the $i$th cluster in the first group,
$i = 1,\ldots,m; j = 1,\ldots,g_i$ and $Y_{kl}$
denote the score for the $l$th subunit from
the $k$th cluster in the second group,
$k=1, \ldots,n;l=1,\ldots,h_k$.
The clustered Wilcoxon rank sum statistic
$W_{c,obs}$ is defined as
\begin{equation} \label{eq:Wco}
W_{c,obs} = \sum_{i=1}^m\sum_{j=1}^{g_i}\text{Rank}(X_{ij})
\end{equation}
where ranks are determined based on the
combined sample of all subunits over the
$X$ and $Y$ clusters. Subunits
for a given cluster are assumed to be exchangeable and each
cluster only contains members from one treatment group.


\subsubsection{Balanced data}\label{brank}
Under balanced designs, the cluster sizes are the same.
Since the score assigned to clusters under treatments
$X$ and $Y$ are
identically distributed under the null hypothesis,
we can pool $X$ and $Y$ clusters together and refer
to a combined set of $Z$ clusters, where $Z_{ij} = $score
for the $j$th subunit of the $i$th cluster,
$j = 1,\ldots,g, i=1,\ldots, m+n = N$.
Under $H_0$,
suppose that $m$ of the $N$ clusters are assigned
at random to the $X$ treatment and the remaining $n$
clusters to the $Y$ treatment.
Let $\delta_i$ be
an indicator function that equals $1$ when the $i$th cluster
is assigned to the $X$ group and $0$ when the $i$th cluster
is assigned to the $Y$ group.
The distribution of the clustered rank sum statistic $W_{c,obs}$ is
\begin{equation}\label{eq:Wc}
W_c = \sum^N_{i=1}\delta_iR_{i+} \quad \text{where   }R_{i+} = \sum^g_{j=1}R_{ij}
\end{equation}

where $R_{ij}=$rank of the $j$th subunit in the
$i$th cluster among all $gN$ subunits over all $Z$ clusters. It is shown that under $H_0$,
\begin{equation}\label{eq:EWc}
E(W_c) = gm(gN + 1)/2
\end{equation}
and
\begin{equation}\label{eq:VWc}
\text{Var}(W_c) = [mn/\{N(N-1)\}]\sum^N_{i=1}\{R_{i+} - g(1+gN)/2\}^2
\end{equation}
So a natural large sample test statistic based on \eqref{eq:Wc}, \eqref{eq:EWc}, and \eqref{eq:VWc} is
\begin{equation}
Z_c = \{W_c - E(W_c)\}/\{\text{Var}(W_c)\}^{1/2}
\end{equation}
$Z_c$ is asymptotically normal if both $m \to \infty$ and $n \to \infty$.
When the sample size is small, permutation test can be
performed.


\subsubsection{Unbalanced data}\label{ubrank}

For unbalanced designs, the null distribution
of the sum of rank
assigned to each cluster are not
identically distributed across clusters
with different sizes.
Let $(m_g, n_g)=$ number of clusters of
size $g$ assigned to the $X$ and $Y$ treatment
respectively.
Denote $N_g = m_g + n_g$ for $g=1,\ldots,g_{max}$
as the total number of clusters for clusters with
size $g$,
and $N =\sum_{g=1}^{g_{max}}N_g$ as the total number
of clusters in the sample.
Let $R_{ij,g} = $ rank for the $j$th
subunit in the $i$th cluster of size $g$,
$g = 1, \ldots, g_{max},
i = 1, \ldots, N_g, j = 1, \ldots, g$,
where $R_{ij,g}$s are computed based on the
combined sample.
The rank sum statistic can then be
written as:
\begin{equation}
W_{c, obs} = \sum_{g=1}^{g_{max}}
\sum_{i\in I_{g, obs}}R_{i+, g}
\end{equation}
where $R_{i+,g}$ = sum of ranks of
all subunits in the $i$th cluster of size $g$,
$i = 1, \ldots, N_g$.
The distribution corresponding to $W_{c, obs}$
is
\begin{equation}
\label{eq:ubrankstat}
W_c = = \sum_{g = 1}^{g_{max}}
 = \sum_{g = 1}^{g_max}\sum_{i = 1}^{N_g}\delta_{i, g}R_{i+, g}
\end{equation}
where $\delta_{i, g} = 1$ if the $i$th
cluster of size $g$ is assigned to group $X$, and is $0$
otherwise.
The corresponding $E(W_c)$ and $\text{Var}(W_c)$ are
as following:
\begin{equation}\label{eq:uEWc}
E(W_c) = \sum_{g=1}^{g_{max}}m_g(R_{++,g}/N_g)
\end{equation}
\begin{equation}\label{eq:uVWc}
\text{Var}(W_c) = \sum_{g=1}^{g_{max}}[m_gn_g/\{N_g(N_g - 1)\}]\sum_{i=1}^{N_g}(R_{i+,g} - R_{++,g}/N_g)^2
\end{equation}
A large-sample test statistics based on $W_c$ is as following:
\begin{equation}
Z_c = \{W_c - E(W_c)\}/\{\text{Var}(W_c)\}^{1/2}
\end{equation}
Again, when sample size is small, permutation test can
be applied based on \eqref{eq:ubrankstat}

When applying the ranksum test for the clustered data,
a formula is used as a interface where the response
variable is on the righthand side and covariates on
the lefthand side. Special functions \code{group},
\code{cluster} and \code{stratum} are used to indicate
the function of each variable, \code{group} indicates
the id of the treatment group, \code{cluster} indicates
the membership of an observation in a specific cluster
and \code{stratum} indicates the stratum an observation
belongs to.

<<rank sum test for unbalanced data>>=
library(clusrank)
data(crd)
## Using large-sample test.
cluswilcox.test(z ~ group(group) + cluster(id), data = crd)
## For small sample, using the permutation test.
cluswilcox.test(z ~ group(group) + cluster(id), data = crd, permutation = TRUE)
@


\subsubsection{Data with Stratification}
Futher more, if the data is also stratified,
the test statistic and its null distribution will
need modification to control for stratification as
an extra
confounding variable.
Suppose there are $V$ strata,
let $(m_{g,v}, n_{g,v})=$ number of clusters of size $g$
in stratum $v$ assigned to the$X$ and $Y$ clusters of size $g$
in stratum $v$ respectively,
$g = 1, \ldots, g_{max}, v = 1, \ldots, V$.
Let $R_{i+, g, v}$ be the rank sum for the subunits in the
$i$th cluster of size $g$ in the $v$th stratum.
The rank sum statistic is defined as

\begin{equation}
\label{eq: srank}
W_{c, obs} = \sum_{g=1}^{g_{max}}\sum_{v=1}^{V}\left(\sum_{i\in I_{g,v,obs}}R_{i+,g,v}\right)
\end{equation}
where $I_{g, v, obs}$ is the observed subset of $m_{g,v}$
unique indices selected from
$\{1, \ldots, N_{g,v}\}$,
corresponding to cluster of
size $g$ in stratum $v$ that are assigned to the $X$ treatment.
The corresponding expectation and variance of the null
distribution of $W_{c, obs}$

\begin{align*}
E(W_c)=& \sum_{g=1}^{g_{max}}\sum^V_{v=1}m_{g,v}R_{++,g,v}/N_{g,v}\\
\text{Var}(W_c)=& \sum_{g=1}^{g_{max}}\sum_{v=1}^V[m_{g,v}n_{g,v}/\{N_{g,v}(N_{g,v} - 1)\}]\\
&\times\sum_{i=1}^{N_{g,v}}(R_{i+, g, v} - R_{++, g, v}/N_{g,v})^2
\end{align*}

The large sample test statistic is then
\begin{equation}
Z_c = \{W_c - E(W_c)\}/\{\text{Var}(W_c)\}^{1/2}.
\end{equation}
Again, permutation test can be applied when sample size is small.

Following is an illustration of the rank sum test for the
stratified data, the \code{crdStr} data is a test data set
comes with the package:
<<rank sum test for stratified data>>=
data(crdStr)
cluswilcox.test(z ~ group(group) + cluster(id) + stratum(stratum), data = crdStr)
@


\subsection{Wilcoxon signed rank test for clustered data}
\label{sign}
\subsubsection{Hypothesis}
\label{hsign}
Let $X_{ij} (Y_{ij})$ denotes the baseline
(follow-up) score for the $j$th subunit
in the $i$th cluster (subject) and
define $Z_{ij} = Y_{ij} - X_{ij}, j = 1,
\ldots,g_i; i = 1,\ldots,m$.
Within each cluster, the difference
scores are assumed to be independent and
identically distributed. The signed rank
test is used to find out if the population
is shifted after the treatment.
Formally, hypothesis being tested is

\begin{equation*}
H_0: \text{the difference score } Z \text{ is symmetric about 0}
\end{equation*}
vs
\begin{equation*}
H_1: Z \text{ is symmetric about }\gamma, \gamma \not = 0.
\end{equation*}

Rank $|Z_{ij}|$ over the total of
$G = \sum_{i=1}^m g_i$ subunits from
the $m$ clusters and let $S_{ij}=R_{ij}V_{ij}$,
where $R_{ij} = $ rank of $|Z_{ij}|$
within the total data set of $G$
subunits over $m$ clusters, and $V_{ij} = \text{sign}(Z_{ij})$.


\subsubsection{Balanced Data}
\label{bsign}
If the data is balanced,
the clustered
Wilcoxon signed rank statistic is defined as following:

\begin{equation}
T_{c}^{(obs)} = \sum_{i=1}^mS_{i+} \equiv \sum^m_{i=1}\sum^g_{j=1}R_{ij}V_{ij},
\end{equation}


where $S_{i+} = \sum_{j=1}^gS_{ij}$ which
is the sum of the rank within $i^{th}$ cluster
and only consider nonzero
$Z_{ij}$ in the computation of signed ranks.
When considering the randomization
distribution corresponding to $T_c$,
the unit of randomization is the cluster.
Let $\delta_1, \ldots,\delta_m$ be i.i.d.
random variables each taking on the values
+1 and -1 with probability 1/2, then the
distribution of $T_{c}^{(obs)}$ is:

\begin{equation} \label{eq:tc}
T_c = \sum_{i=1}^m\delta_iS_{i+}.
\end{equation}

It is shown that under $H_0$, $E(T_c) = 0$
and $\text{Var}(T_c) = \sum^m_{i=1}S^2_{i+}$.
Standarize $T_{c}^{(obs)}$ with $E(T_c)$ and
$\text{Var}(T_c)$,
the large sample test statistic is defined as
\begin{equation}
Z_c = \left. T_c \middle/ \left(\sum_{i=1}^nS^2_{i+}\right)^{1/2}\right. \sim N(0, 1)\qquad \text{under } H_0.
\end{equation}
When the sample size is small, a permutation
test can be applied.


For the signed rank test, the input should be a numeric
vector which contains the difference between the paired
observations, or two vectors, where vector
\code{x} contains observations before the treatment,
and \code{y} contains observations after the treatment.
This manner of input is restricted to the signed rank
test.

%' <<signed rank test for balanced data>>=
%' ## Large sample signed rank test for clustered data
%' data(crsd)
%' cluswilcox.test(z, cluster = id, data = crsd)
%' ## Small sample test
%' data(crsd)
%' cluswilcox.test(z, cluster = id, data = crsd, permutation = TRUE)
%' @

\subsubsection{Unbalanced Data}
\label{ubsign}
When the data is unbalanced
the test statistic is defined as:

\begin{equation}
T_c^{(obs)} = \sum_{i = 1}^m w_i\bar{S}_i
\end{equation}

where $\bar{S}_i = S_{i+}/{g_i}, w_i = 1/\text{Var}(\bar{S}_i)$ under $H_0$.
The randomization distribution
corresponding to
$T_{c,s}^{obs} = \sum^m_{i=1}\delta_iw_i\bar{S}_i$.
$\delta$ is defined as in \eqref{eq:tc}.
The test statistic is defined as
\begin{equation}
Z_{c,s} = \left.T_{c,s}\middle/ \left(\sum_{i=1}^m\hat{w}^2_i\bar{S}^2_i\right)^{1/2}\right. \sim N(0,1) \text{ under }H_0,
\end{equation}

where $\hat{w}_i = g_i/[\widehat{Var}(S_{ij})\{1 + (g_i-1)\hat{\rho}_{s,cor}\}]$, $\hat{\rho}_{s,cor} = \hat{\rho}_s\left(1 + \frac{1 - \hat{\rho}_s^2}{m - 5/2}\right)$,$\hat{\rho_s} = $ max $[\hat{\sigma}_A^2/(\hat{\sigma}_A^2 + \hat{\sigma}^2), 0]$, $\hat{\sigma
}^2 = \sum_{i=1}^m\sum_{j=1}^{g_i}(S_{ij} - \bar{S}_i)^2/(G-m), \hat{\sigma}^2_A = $ max $[\{\sum_{i=1}^mg_i(\bar{S_i}- \bar{\bar{S}})^2/(m-1)- \hat{\sigma}^2\}/g_0,0], g_0 = [\sum_{i=1}^mg_i - \sum_{i=1}^mg_i^2/\sum_{i=1}^mg_i]/(m-1)$ and $\widehat{Var}(S_{ij}) = \sum_{i=1}^m\sum_{j=1}^{g_i}(S_{ij} - \bar{\bar{S}})^2/(G-1)$.

An illustration of use of the test is as following:
<<signed rank test for unbalanced data>>=
data(crsdUnb)
cluswilcox.test(z, cluster = id, data = crsdUnb)
@



\section{Real Data Analysis}
\label{real}

%' \subsection{Data}
%' To illustrate the usage of the package, we are going to
%' perform the clustered Wilcoxon rank sum test on a
%' real data set in a study of eyes.
%' Age-related macular degeneration (AMD) is a disease
%' that blurs the sharp centeral vision by
%' affecting macula, a oval yellow spot
%' near the center of the retina of the human eye.
%' The complement factor H R1210C is a large protein
%' that circulates in human plasma. The variant of
%' this protein confers the strongest genetic risk
%' for AMD and earlier age at onset. The objective
%' of the study is to characterize the observable
%' traits of this variant. The study was carried out by
%' the Seddon Lab \citep{Sedd:Shar:Adel:eval:2006,
%' Ferr:Sedd:phen:2015} with 143 patients (283 eyes)
%' involved, including 62 patients with the rare
%' variant. The degree of severity of AMD was graded
%' based on the Clinical
%' Age-Related Maculopathy Staging (CARMS) system for
%' each enrolled eye.
%' The CARMS system has a
%' 5-step scale, where 1 to 3 represent no symptom,
%' earlier and intermediate severity respectively,
%' 4 and 5 represent
%' two different symptoms of the advanced AMD,
%' geographic atrophy and neovascular disease respectively.
%' The
%' CARMS grades were assessed separately for these
%' two advanced stages, i.e., we are going
%' to carry out the analysis on two subsets of the
%' observations respectively: the subset of
%' observations with
%' CARMS grade 1, 2, 3, or 4, and the subset of
%' observations with CARMS grade 1, 2, 3, or 5.
%' Since high correlation between
%' eyes of the same patient is expected while
%' observations from different patients can be assumed
%' as independent, the data is clustered in pairs and
%' each subject is a cluster. The data also provided
%' information on age and sex, and an extra variable
%' combined age and sex, which could be used to stratify
%' the data.
%' In this analysis, the CARMS grade is the response
%' variable and treatment refers to the presence
%' of the complement factor H R1210C variant.
%' The data set contains 7 variables: ID is the
%' subject identifier which is the cluster id.
%' 
%' 
%' <<CARMS score 1, 2, 3, 4>>=
%' ## Carry out clustered rank sum test for the subset
%' ## with CARMS grade 1, 2, 3 and 4.
%' data(sedlab)
%' cluswilcox.test(CARMS ~ cluster(ID) + stratum(Agesex) + group(Variant),
%'                 data = sedlab, subset = CARMS %in% c(1, 2, 3, 4))
%' @
%' 
%' <<CARMS score 1, 2, 3, 5>>=
%' ## Carry out clustered rank sum test for the subset
%' ## with CARMS grade 1, 2, 3 and 5.
%' data(sedlab)
%' cluswilcox.test(CARMS ~ cluster(ID) + stratum(Agesex) + group(Variant),
%'                 data = sedlab, subset = CARMS %in% c(1, 2, 3, 5))
%' @
%' 
%' When controlled for the stratification covariate \code{Agesex},
%' the p-value for CARMS grades 1-4 is less than $0.001$,
%' which implies strong correlation between the
%' presence of the complement factor H R1210C variant and
%' the severity of AMD when treating geographic atrophy as the
%' advanced stage. The p-value for CARMS grades 1,2,3 and 5
%' is 0.06, again the evidence is relatively strong the
%' the presence of the variant does affect the severity of
%' AMD when treating neovascular disease as the advanced stage.





\section{Summary}
\label{summ}
In this artical, Wilcoxon rank sum test and Wilcoxon signed rank
test adjusted for the clustering effect in the data are
introduced. The usage of the \proglang{R} package \pkg{clusrank} carrying out the
two tests is illustrated with examples.
Both the tests are able to handel unbalanced data.
In addition, the clustered Wilcoxon rank sum test also permits an
extra covariate as stratification variable.
\section*{Acknowledgement}
Data \textbf{sedlab} is provided by Seddon Lab
\citep{Sedd:Shar:Adel:eval:2006,
Ferr:Sedd:phen:2015}.
%% Note: If there is markup in \(sub)section, then it has to be escape as above.


%\bibliographystyle{jss}

\bibliography{clusrank}

\end{document}
