################################################################################
##
##   R package clusrank by Mei-Ling Ting Lee, Jun Yan, and Yujing Jiang
##   Copyright (C) 2020-2017
##
##   This file is part of the R package clusrank.
##
##   The R package clusrank is free software: you can redistribute it and/or
##   modify it under the terms of the GNU General Public License as published
##   by the Free Software Foundation, either version 3 of the License, or
##   (at your option) any later version.
##
##   The R package clusrank is distributed in the hope that it will be useful,
##   but WITHOUT ANY WARRANTY without even the implied warranty of
##   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##   GNU General Public License for more details.
##
##   You should have received a copy of the GNU General Public License
##   along with the R package clusrank. If not, see <http://www.gnu.org/licenses/>.
##
################################################################################


# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Fprop <- function(x, clus, nvec, m, n) {
    .Call('_clusrank_Fprop', PACKAGE = 'clusrank', x, clus, nvec, m, n)
}

Fi <- function(X, I, x, clus, nvec, N) {
    .Call('_clusrank_Fi', PACKAGE = 'clusrank', X, I, x, clus, nvec, N)
}

Ftot <- function(X, x, clus, nvec, N, M) {
    .Call('_clusrank_Ftot', PACKAGE = 'clusrank', X, x, clus, nvec, N, M)
}

Ftot_vec <- function(x, clus, nvec, N, M) {
    .Call('_clusrank_Ftot_vec', PACKAGE = 'clusrank', x, clus, nvec, N, M)
}

Fi_vec <- function(x, clus, nvec, N, M) {
    .Call('_clusrank_Fi_vec', PACKAGE = 'clusrank', x, clus, nvec, N, M)
}

Fcom <- function(X, x, clus, nvec, N, M) {
    .Call('_clusrank_Fcom', PACKAGE = 'clusrank', X, x, clus, nvec, N, M)
}

Fcom_vec <- function(x, clus, nvec, N, M) {
    .Call('_clusrank_Fcom_vec', PACKAGE = 'clusrank', x, clus, nvec, N, M)
}

cumcrksum <- function(rks, I, Score, Csize) {
    .Call('_clusrank_cumcrksum', PACKAGE = 'clusrank', rks, I, Score, Csize)
}

crksum_str <- function(k, x, xc, max) {
    .Call('_clusrank_crksum_str', PACKAGE = 'clusrank', k, x, xc, max)
}

pcrksum_str <- function(k, x, xc, xn, n, max) {
    .Call('_clusrank_pcrksum_str', PACKAGE = 'clusrank', k, x, xc, xn, n, max)
}

psrkg <- function(srk, Score) {
    .Call('_clusrank_psrkg', PACKAGE = 'clusrank', srk, Score)
}

