# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crksum <- function(rks, I, J, sumrks, minrks) {
    .Call('clusrank_crksum', PACKAGE = 'clusrank', rks, I, J, sumrks, minrks)
}

pcrksum <- function(rks, I, Score) {
    .Call('clusrank_pcrksum', PACKAGE = 'clusrank', rks, I, Score)
}

cumcrksum <- function(rks, I, Score) {
    .Call('clusrank_cumcrksum', PACKAGE = 'clusrank', rks, I, Score)
}

crksum_str <- function(k, x, xc, max) {
    .Call('clusrank_crksum_str', PACKAGE = 'clusrank', k, x, xc, max)
}

pcrksum_str <- function(k, x, xc, xn, n, max) {
    .Call('clusrank_pcrksum_str', PACKAGE = 'clusrank', k, x, xc, xn, n, max)
}

test <- function(depth, max) {
    invisible(.Call('clusrank_test', PACKAGE = 'clusrank', depth, max))
}

csrkg <- function(srk, Score) {
    .Call('clusrank_csrkg', PACKAGE = 'clusrank', srk, Score)
}

psrkg <- function(srk, Score) {
    .Call('clusrank_psrkg', PACKAGE = 'clusrank', srk, Score)
}

Fprop <- function(x, clus, nvec, m, n) {
    .Call('clusrank_Fprop', PACKAGE = 'clusrank', x, clus, nvec, m, n)
}

Fi <- function(X, I, x, clus, nvec, N) {
    .Call('clusrank_Fi', PACKAGE = 'clusrank', X, I, x, clus, nvec, N)
}

Ftot <- function(X, x, clus, nvec, N, M) {
    .Call('clusrank_Ftot', PACKAGE = 'clusrank', X, x, clus, nvec, N, M)
}

Ftot_vec <- function(x, clus, nvec, N, M) {
    .Call('clusrank_Ftot_vec', PACKAGE = 'clusrank', x, clus, nvec, N, M)
}

Fi_vec <- function(x, clus, nvec, N, M) {
    .Call('clusrank_Fi_vec', PACKAGE = 'clusrank', x, clus, nvec, N, M)
}

Fcom <- function(X, x, clus, nvec, N, M) {
    .Call('clusrank_Fcom', PACKAGE = 'clusrank', X, x, clus, nvec, N, M)
}

Fcom_vec <- function(x, clus, nvec, N, M) {
    .Call('clusrank_Fcom_vec', PACKAGE = 'clusrank', x, clus, nvec, N, M)
}

