library(clsrank)
data(crsd)
clusignrank(z, id, data = crsd)
data(crsd.unb)
clusignrank(z, id, data = crsd.unb)
data(crd)
cluswilcox(z ~ group, data = crd, id = id)
data(crd.str)
cluswilcox(z ~ group, data = crd.str, id = id, stratum = stratum)